env: development


provider: ${ACTIVE_PROVIDER}

llm:
  openai:
    api_key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL} # gpt-4o
  
  openrouter:
    api_key: ${OPENROUTER_API_KEY}
    model: ${OR_MODEL}
    base_url: "https://openrouter.ai/api/v1"

  ollama:
    base_url: ${OLLAMA_URL} # http://localhost:11434/v1
    api_key: "none"
    model: "llama3"

