package translator

import (
	"runtime"
	"strings"

	"github.com/SecDuckOps/agent/internal/domain"
	"github.com/SecDuckOps/agent/internal/ports"
)

// OSTranslatorAdapter implements the OSTranslatorPort.
// It maps generic UNIX-like commands (ls, cat, rm) generated by the LLM
// into the corresponding native OS commands.
type OSTranslatorAdapter struct {
	goos string
}

// NewOSTranslatorAdapter creates a translator aware of the current operating system.
// If osOverride is empty, it uses the actual runtime.GOOS.
func NewOSTranslatorAdapter(osOverride string) ports.OSTranslatorPort {
	if osOverride == "" {
		osOverride = runtime.GOOS
	}
	return &OSTranslatorAdapter{goos: osOverride}
}

// Translate converts the command and arguments.
func (t *OSTranslatorAdapter) Translate(task *domain.OSTask) {
	// 1. Argument Filtering: Remove empty strings that cause "Invalid switch" on Windows
	filteredArgs := make([]string, 0, len(task.Args))
	for _, arg := range task.Args {
		if arg != "" {
			filteredArgs = append(filteredArgs, arg)
		}
	}
	task.Args = filteredArgs

	if t.goos == "windows" {
		t.translateForWindows(task)
	}

	// For linux/darwin (UNIX), the command is likely already correct
}

// translateForWindows attempts to map UNIX shell commands to
// cmd.exe builtins, powershell builtins, or native Windows equivalents.
func (t *OSTranslatorAdapter) translateForWindows(task *domain.OSTask) {
	// A basic alias map for LLM UNIX habits -> Windows cmd.exe built-ins
	unixToWindows := map[string]string{
		"ls":    "dir",
		"cat":   "type",
		"rm":    "del",
		"cp":    "copy",
		"mv":    "move",
		"pwd":   "cd",
		"clear": "cls",
		"grep":  "findstr",
	}

	mappedCmd, exists := unixToWindows[task.OriginalCmd]
	if !exists {
		// If it's not a common built-in, assume it's a regular executable (like "git" or "go")
		return
	}

	// Detect UNC path (e.g. \\wsl.localhost\...). 
	// cmd.exe /c does not support starting in a UNC directory.
	// powershell.exe -Command does.
	isUNC := strings.HasPrefix(task.Cwd, `\\`)
	
	executor := "cmd.exe"
	executorArgs := []string{"/c", mappedCmd}
	
	if isUNC {
		executor = "powershell.exe"
		executorArgs = []string{"-Command", mappedCmd}
	}

	// Convert some common UNIX flags to Windows flags where possible.
	for _, arg := range task.Args {
		if task.OriginalCmd == "ls" {
			if strings.Contains(arg, "-l") || strings.Contains(arg, "-a") {
				continue // Skip UNIX ls flags for Windows dir
			}
		}
		if task.OriginalCmd == "rm" {
			if strings.Contains(arg, "-r") || strings.Contains(arg, "-f") {
				// rm -rf -> del /s /q
				executorArgs = append(executorArgs, "/s", "/q")
				continue
			}
		}
		executorArgs = append(executorArgs, arg)
	}

	task.OriginalCmd = executor
	task.Args = executorArgs
}

// Normalize unwraps platform-specific command wrappers to extract the intended command.
func (t *OSTranslatorAdapter) Normalize(cmd string, args []string) (string, []string) {
	if strings.EqualFold(cmd, "cmd.exe") && len(args) >= 2 && strings.EqualFold(args[0], "/c") {
		return args[1], args[2:]
	}
	if strings.EqualFold(cmd, "powershell.exe") && len(args) >= 2 && strings.EqualFold(args[0], "-Command") {
		return args[1], args[2:]
	}
	return cmd, args
}
