package translator

import (
	"runtime"
	"strings"

	"github.com/SecDuckOps/agent/internal/ports"
)

// OSTranslatorAdapter implements the OSTranslatorPort.
// It maps generic UNIX-like commands (ls, cat, rm) generated by the LLM
// into the corresponding native OS commands.
type OSTranslatorAdapter struct {
	goos string
}

// NewOSTranslatorAdapter creates a translator aware of the current operating system.
// If osOverride is empty, it uses the actual runtime.GOOS.
func NewOSTranslatorAdapter(osOverride string) ports.OSTranslatorPort {
	if osOverride == "" {
		osOverride = runtime.GOOS
	}
	return &OSTranslatorAdapter{goos: osOverride}
}

// Translate converts the command and arguments.
func (t *OSTranslatorAdapter) Translate(cmd string, args []string) (string, []string) {
	if t.goos == "windows" {
		return t.translateForWindows(cmd, args)
	}

	// For linux/darwin (UNIX), the command is likely already correct
	return cmd, args
}

// translateForWindows attempts to map UNIX shell commands to
// cmd.exe builtins or native Windows equivalents.
func (t *OSTranslatorAdapter) translateForWindows(cmd string, args []string) (string, []string) {
	// A basic alias map for LLM UNIX habits -> Windows cmd.exe built-ins
	unixToWindows := map[string]string{
		"ls":    "dir",
		"cat":   "type",
		"rm":    "del",
		"cp":    "copy",
		"mv":    "move",
		"pwd":   "cd",
		"clear": "cls",
		"grep":  "findstr",
	}

	mappedCmd, exists := unixToWindows[cmd]
	if !exists {
		// If it's not a common built-in, assume it's a regular executable (like "git" or "go")
		// We don't prepend cmd.exe for regular programs
		return cmd, args
	}

	// For built-ins (dir, type, del), we run them through powershell.exe -Command
	newArgs := []string{"-Command", mappedCmd}
	
	// Convert some common UNIX flags to Windows flags where possible.
	// This is basic for now; complex flag translation requires a deeper engine.
	for _, arg := range args {
		// Clean out UNIX flags that Windows built-ins don't understand or map them
		if cmd == "ls" {
			if strings.Contains(arg, "-l") || strings.Contains(arg, "-a") {
				continue // Skip UNIX ls flags for Windows dir
			}
		}
		if cmd == "rm" {
			if strings.Contains(arg, "-r") || strings.Contains(arg, "-f") {
				// rm -rf -> del /s /q
				newArgs = append(newArgs, "/s", "/q")
				continue
			}
		}
		newArgs = append(newArgs, arg)
	}

	return "powershell.exe", newArgs
}

// Normalize unwraps platform-specific command wrappers to extract the intended command.
func (t *OSTranslatorAdapter) Normalize(cmd string, args []string) (string, []string) {
	if strings.EqualFold(cmd, "cmd.exe") && len(args) >= 2 && strings.EqualFold(args[0], "/c") {
		return args[1], args[2:]
	}
	if strings.EqualFold(cmd, "powershell.exe") && len(args) >= 2 && strings.EqualFold(args[0], "-Command") {
		return args[1], args[2:]
	}
	return cmd, args
}
